# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kusion < Formula
  desc "Codify and deliver intentions to Kubernetes and Clouds"
  homepage "https://github.com/KusionStack/kusion"
  version "0.9.1"
  license "Apache License"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/KusionStack/kusion/releases/download/v0.9.1/kusion_0.9.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d89586fcb4e0c745690cf666bbaa4a69a044072b22652d08728ec51a7825e1ce"

      def install
        bin.install "kusion"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KusionStack/kusion/releases/download/v0.9.1/kusion_0.9.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "74abd467861c36f40502028cde35b66223ee647b5796c253822379075f366ddb"

      def install
        bin.install "kusion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/KusionStack/kusion/releases/download/v0.9.1/kusion_0.9.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "4c11bb65fea35c11b0bc85fb0b198b53d95d1603c2f9e00958c41b48d15ced8c"

      def install
        bin.install "kusion"
      end
    end
  end

  test do
    system "#{bin}/kusion version"
  end
end