# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kusion < Formula
  desc "Codify and deliver intentions to Kubernetes and Clouds"
  homepage "https://github.com/KusionStack/kusion"
  version "0.8.2"
  license "Apache License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KusionStack/kusion/releases/download/v0.8.2/kusion_0.8.2_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "930a31eef6ee5a4ece8b9f1c0c64eb92cab5ca77340c2c27bdbdf462dff94f95"

      def install
        bin.install "kusion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KusionStack/kusion/releases/download/v0.8.2/kusion_0.8.2_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c26ebeeb881ba11a6174c66633003de64272fe7002a9e649564af4de9998e683"

      def install
        bin.install "kusion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/KusionStack/kusion/releases/download/v0.8.2/kusion_0.8.2_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "11da8ce9c2ad41fb2bfd96dc14172f8990a8687b8e572c7aabe5ddf6ad1d09d0"

      def install
        bin.install "kusion"
      end
    end
  end

  test do
    system "#{bin}/kusion version"
  end
end
