# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kusionup < Formula
  desc "A version management tool for kusion"
  homepage "https://github.com/KusionStack/kusionup"
  version "0.2.8-alpha.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KusionStack/kusionup/releases/download/v0.2.8-alpha.6/kusionup_0.2.8-alpha.6_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "858bf126a6ac722d8da0dbd53d12a1be8baa9e9cac8ad9c6c0056361ea616069"

      def install
        bin.install "kusionup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KusionStack/kusionup/releases/download/v0.2.8-alpha.6/kusionup_0.2.8-alpha.6_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "0e3fb33becebe0e6075822dd41f2377557e5201c8f8b3260e4204d25cbc7e80c"

      def install
        bin.install "kusionup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KusionStack/kusionup/releases/download/v0.2.8-alpha.6/kusionup_0.2.8-alpha.6_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "500153923b9402681fc1fda2f77edadb3942f9e7798dcc0428b0d240e7ce1715"

      def install
        bin.install "kusionup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KusionStack/kusionup/releases/download/v0.2.8-alpha.6/kusionup_0.2.8-alpha.6_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "24d2c36864a005d6e403db0203d930ec12d31a54104f90a635324a6dde90e5ae"

      def install
        bin.install "kusionup"
      end
    end
  end

  test do
    system "#{bin}/kusionup version"
  end
end
