# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kusionup < Formula
  desc "A version management tool for kusion"
  homepage "https://github.com/KusionStack/kusionup"
  version "0.2.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/KusionStack/kusionup/releases/download/v0.2.17/kusionup_0.2.17_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "3f18c07d759d7dd3b1427eaef3f03cd384bc665d22111ed7e5446b0fd8477495"

      def install
        bin.install "kusionup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KusionStack/kusionup/releases/download/v0.2.17/kusionup_0.2.17_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "ff526506bd1d0b8a8d55636e5128fe1f3d9f60933e83bcd47200cb58f3acbdff"

      def install
        bin.install "kusionup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/KusionStack/kusionup/releases/download/v0.2.17/kusionup_0.2.17_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "de1c6c22a619fee6df3f87c0099e3a326dc19b7a147d25a1d3787b17ab15a0a4"

      def install
        bin.install "kusionup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KusionStack/kusionup/releases/download/v0.2.17/kusionup_0.2.17_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "513519b93a68ab2aeb192ef79a361f62a8ac8d7d06084098e1d25d38a4336881"

      def install
        bin.install "kusionup"
      end
    end
  end

  test do
    system "#{bin}/kusionup version"
  end
end
